language: java
jdk:
  - oraclejdk8
  - openjdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
install: true
script: mvn clean install
cache:
  directories:
  - $HOME/.m2
branches:
  only: 
    - CI
