language: java
jdk:
  - openjdk8
services:
  - mysql
before_install:
  - chmod +x scripts/
  - sudo mysql -uroot -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('example');FLUSH PRIVILEGES;"
  - sudo service mysql restart
  - sudo mysql -u root -pexample -e "start transaction;create database db_springboot;grant select, insert, update, delete,  create, drop, references, index, alter, create temporary tables, lock tables, create view, create routine, alter routine, execute, trigger, show view on db_springboot.* to 'root'@'localhost';commit;"
install: true
script: mvn clean install
cache:
  directories:
  - $HOME/.m2
branches:
  only:
    - CI
after_success:
  - "sh scripts/merge_branch.sh"
